### ISSUE TITLE
构建提示dtkwidget development package not found.

### ISSUE THREAD

**Issue by jackyting825** [rekols/kugou-music#1]
刚接触QT,想clone下你的项目代码学习下,但是项目导入到qt creator后,构建提示:dtkwidget development package not found.请问一下这个怎么破?我的环境是deepin 15.5 ,qt是用sudo apt install qt5-default qt5-qmake安装的.项目构建配置如图:
![qq 20180306152047](https://user-images.githubusercontent.com/8901160/37019225-79481274-2152-11e8-86f6-d50dd649582a.png)

**Comment by reionwong** [comment]
sudo apt install libdtkcore-dev libdtkwidget-dev

安装再试试。

**Comment by jackyting825** [comment]
安装后,不知道是不是改过哪儿配置,构建出现这个问题了
![qq 20180306172759](https://user-images.githubusercontent.com/8901160/37024455-deb52fbe-2163-11e8-8aca-a5f95ec75ea2.png)

**Comment by reionwong** [comment]
你直接在源码打开终端输入：
mkdir build && cd build && qmake .. && make && ./kugou-music

**Comment by jackyting825** [comment]
谢谢,我知道出现刚刚那个问题的原因了.是我在构建里面选择C和C++的编译器的地方选择的版本不一致的问题.因为有另外一个项目是QT4版本的,我环境下安装了4和5两个版本,所以时不时的要去更改QT版本,可能无意中鼠标滚轮把C和C++的编译器的选项给更改了,就导致了构建的时候找不到对应的模块了. 
![qq 20180306181121](https://user-images.githubusercontent.com/8901160/37026588-d358ffb4-2169-11e8-8435-d70a49fad283.png)
